### PR TITLE
Rewrite CircleCI config to new 2.0 format

### LINKED ISSUE #99: Fix Circle CI config file and make a new release
Hi,

Would it be possible to fix the Circle CI config file, which is broken because Circle CI v1 has been turned off and replaced by Circle CI v2 (which has a completely different syntax)? I've try to take a stab at it but I've never used CircleCI before (I use Jenkins and Github action). In particular, I couldn't get CircleCi to run the bash scripts for building and deploying.

It would be great to be able to make a new release now that @saattrupdan has made the code base compatible with scikit-learn > 0.22.

Thanks!

### PR DESCRIPTION
**Pull request by ecederstrand**
Fixes #99

### CODE REVIEW

**Comment by ecederstrand** [comment]
@MechCoder I have only very little overview of what the CircleCi script is supposed to do, but here's an attempt at rewriting the circle.yml to 2.0 syntax. I found some help in https://circleci.com/docs/2.0/migration/

It passes the CircleCI run now, but it's probably a good idea to check that the run still does what it's supposed to do.

**Comment by ecederstrand** [comment]
Ping @MechCoder

**Review by Bougeant — APPROVED** [review]
Amazing. I've been trying to do this myself without much success.

**Comment by Bougeant** [comment]
Are tests actually being run?

**Comment by ecederstrand** [comment]
No idea. The three scripts mentioned in the script previously are still run, as seen in https://app.circleci.com/pipelines/github/scikit-garden/scikit-garden/30/workflows/b5f4f064-7238-41ff-b195-eaf2b0d8ea55/jobs/239/steps

**Comment by ecederstrand** [comment]
@MechCoder Any chance you can have a look at this? I believe the new config file triggers the same scripts as previously.

**Comment by MechCoder** [comment]
Sorry for the delay. The tests are being run but it seems like the website is not being pushed. (https://app.circleci.com/pipelines/github/scikit-garden/scikit-garden/30/workflows/b5f4f064-7238-41ff-b195-eaf2b0d8ea55/jobs/239/steps). I will try and have a look later.

**Pull request merged**
