### PR TITLE
Allow source install without build deps preinstall

### PR DESCRIPTION
**Pull request by ecederstrand**
This solves the issue where installing scikit-garden in an empty virtualenv does not work.

Adds numpy as setup requirements, and requires Cython only when running the build_ext, where Cython is needed. This pushes the Cython requirement to a point in the install where setuptools has had time to install Cython as a build requirement.

Replaces #77 which forgot to cythonize extensions.

With this PR, I can do this without errors:

```bash
# git clone https://github.com/ecederstrand/scikit-garden.git
# cd scikit-garden
# git checkout patch-1

python3 -m venv tmp
source tmp/bin/activate
python3 -m pip install wheel
python3 setup.py build_ext bdist_wheel
```

Also added support for scikit-learn master branch, to satisfy test suite.

### CODE REVIEW

**Comment by ecederstrand** [comment]
`test_forest.test_parallel_train` is failing. I have no idea how to fix it. I don't think it's related to the original task in this PR.

**Comment by ecederstrand** [comment]
@glouppe Ping?

**Comment by saattrupdan** [comment]
@ecederstrand I faced the same failing test in https://github.com/scikit-garden/scikit-garden/pull/89 and ended up concluding that running the parallel training with more than 1 process on Travis CI's VM causes memory overload, forcing it to drop a worker, yielding the failing test. I simply commented out the test, and I guess it should really just be removed, to be able to use Travis.

**Comment by ecederstrand** [comment]
@MechCoder Can you have a look at this one?

The CircleCi build is failing, but the master branch has the same issue. It seems like the circle.yml format is outdated.

**Comment by ecederstrand** [comment]
@MechCoder I'm running through our collection of patches. Just wondering whether you have any comments to this PR?

**Comment by MechCoder** [comment]
Thanks for your help! Do you have a hint on why the CircleCl fails? Did the syntax or something change? (https://discuss.circleci.com/t/incorrect-validation-of-config-yml/22793)

**Comment by ecederstrand** [comment]
It seems the current CircleCI syntax is entirely different. Here's an example of the new syntax: https://circleci.com/docs/2.0/language-python/#install-dependencies

I don't have any experience with CircleCI so I'd have to do some trial-and-error to find a working config, but this PR is probably not the best place to do that.

**Comment by ecederstrand** [comment]
Maybe you could start with what scikit-learn has now? https://github.com/scikit-learn/scikit-learn/blob/main/.circleci/config.yml

**Comment by ecederstrand** [comment]
@MechCoder After #100 was merged, this one should also be ready to merge now.

**Pull request merged**
