### PR TITLE
Dependency fix

### PR DESCRIPTION
**Pull request by saattrupdan**
Updated the imports to their current versions. Specifically:

1. `sklearn.externals.joblib` is replaced with `joblib`
2. `sklearn.utils.testing` is replaced with `numpy.testing`
3. `sklearn.externals.six` is replaced with `six`
4. `sklearn.tree.tree` is replaced with `sklearn.tree`
5. `presort` parameter removed from calls to `DecisionTreeRegressor`
6. Replaced occurences of `assert_true`, `assert_false`, `assert_greater` and `assert_less` with their equivalent `assert` statements
7. As `ForestClassifier` and `ForestRegressor` can't be imported from `sklearn` anymore, the source code for these are now placed in `forest.py`

All unit tests in `tests/`, `mondrian/tree/tests/`, `mondrian/ensemble/tests` and `quantile/tests` run with no errors.

### CODE REVIEW

**Comment by Bougeant** [comment]
Is there a chance we can land this? I'm happy to review if needed.

**Review by Bougeant — APPROVED** [review]
Looks good to me

**Review by PSSF23 — APPROVED** [review]
Thanks for making it work again! Really appreciate it!

**Comment by PSSF23** [comment]
@MechCoder It will be great if this PR could be merged!

**Comment by lnpsiqueira** [comment]
Hello,
Did anybody got this error?

rfqr = RandomForestQuantileRegressor(random_state=0)
Traceback (most recent call last):

  File "<ipython-input-60-cbc050ad69ed>", line 1, in <module>
    rfqr = RandomForestQuantileRegressor(random_state=0)

  File "C:\Users\HerrSiqueira\anaconda3\envs\mestrado\lib\site-packages\skgarden\quantile\ensemble.py", line 295, in __init__
    base_estimator=DecisionTreeQuantileRegressor(),

  File "C:\Users\HerrSiqueira\anaconda3\envs\mestrado\lib\site-packages\skgarden\quantile\tree.py", line 222, in __init__
    super(DecisionTreeQuantileRegressor, self).__init__(

TypeError: super(type, obj): obj must be an instance or subtype of type

**Pull request merged**
