### PR TITLE
Add local versions of fmax and fmin

### LINKED ISSUE #41: fmin, fmax don't work on Windows in Python 2.7
`libc.math.{fmin,fmax}`, used in [`mondrian.tree._tree`](https://github.com/scikit-garden/scikit-garden/blob/d6c3d6d9c15f3fc8c959018dc3ff532fb5193eee/skgarden/mondrian/tree/_tree.pyx), are C99 functions that [don't work in old Visual Studio versions](https://stackoverflow.com/questions/40737873/fmax-and-fmin-alternative-in-c89) like the one you need to use to build Python 2.7 extensions. So the build fails with a linker error on Windows for 2.7; [example build log](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.15318/job/k3f7ws3wo3vk40wh) from https://github.com/conda-forge/staged-recipes/pull/3352.

Probably the easiest thing to do is to write little helper functions, e.g.
```python
cdef inline double fmax(double left, double right):
    return left if left > right else right

cdef inline double fmin(double left, double right):
    return left if left < right else right
```
and either figure out how to only use them on Windows or just always use them.

### PR DESCRIPTION
**Pull request by betatim**
Fixes #41

### CODE REVIEW

**Comment by betatim** [comment]
Looks like this builds fine, locally all tests also passed on my mac.

@dougalsutherland do you know anything more on this topic/potential pitfalls? Otherwise time to merge and release a new version for https://github.com/conda-forge/staged-recipes/pull/3352

**Comment by dougalsutherland** [comment]
Seems fine, though is that the only place they're used? I vaguely remember them showing up somewhere else too, I thought.

Might be worth seeing up AppVeyor and running the test suite on Windows here directly before releasing, to catch any other Windows problems that might crop up after this one is fixed without iterating through tons of releases and conda-forge's infrastructure. :)

**Comment by dougalsutherland** [comment]
(But no, I don't particularly know anything about Windows, just caught that error reviewing the conda-forge PR.)

**Comment by glouppe** [comment]
Merging this, thanks :)

**Comment by betatim** [comment]
> Might be worth seeing up AppVeyor and running the test suite on Windows

-> #45, I think the biggest hurdle is that none of us actually use windows 😢 let's see what we can do.

Did a quick grep for `fmin` and `fmax` seems like they are confined to `tree.pyx`.

**Pull request merged**
